### PR TITLE
feat: Add deployment repository

### PR DESCRIPTION
**Pull request by GliczDev**
### What does this PR do?
Adds deployment repository
<hr>

The only problem is that I'm not sure how should I configure Jenkinsfile for deployment
https://github.com/eclipse/tm4e/blob/d77316439d39a8254a455f207dbb4c582968a9e2/Jenkinsfile#L28
should I add `deploy` goal here?

### CODE REVIEW

**Comment by sebthom** [comment]
> ### What does this PR do?
> 
> Adds deployment repository
> 
> The only problem is that I'm not sure how should I configure Jenkinsfile for deployment
> 
> https://github.com/eclipse/tm4e/blob/d77316439d39a8254a455f207dbb4c582968a9e2/Jenkinsfile#L28
> 
> should I add `deploy` goal here?

no, this job is only for snapshot builds. 

Release builds are done by https://ci.eclipse.org/tm4e/job/promote-snapshot-to-release/ but I don't know what/how to change it so it deploys to maven central.

**Comment by GliczDev** [comment]
> Thanks for your PR. For being able to process this PR, you need to [sign](https://accounts.eclipse.org/user/login?destination=user/eca) the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

done

> deploys to maven central.

wdym maven central? my PR adds repo.eclipse.org tm4e deployment repository. 

> Release builds are done by https://ci.eclipse.org/tm4e/job/promote-snapshot-to-release/ but I don't know what/how to change it so it deploys to maven central.

I think adding `mvn deploy` should be enough, but I don't use maven so I'm not sure.

**Comment by sebthom** [comment]
> I think adding `mvn deploy` should be enough, but I don't use maven so I'm not sure.

adding deploy here will still only publish to the snapshot repo as this Jenkins job is not used to create releases.
also it would unnecessarily publish all modules to the snapshot repo, not only the core module.
I am going to prepare a separate PR that only publishes the core module.

**Comment by sebthom** [comment]
Thanks for the PR!

**Pull request merged**
