### PR TITLE
Update Maven plugins.

### PR DESCRIPTION
**Pull request by akurtakov**

### CODE REVIEW

**Comment by angelozerr** [comment]
@mickaelistria @pascalleclercq could you review this PR. Thanks!

**Comment by pascalleclercq** [comment]
Looks good to me.
I can't merge It because I don't have write access to the repo.
@mickaelistria @angelozerr Can I have write access ?

**Comment by mickaelistria** [comment]
+1 too.
I also don't have permissiosn to push on this repo.

**Comment by angelozerr** [comment]
Ok thanks guys.

> I also don't have permissiosn to push on this repo.

Me too:) I'm waiting for answer of webmaster

**Comment by angelozerr** [comment]
No I can't @pascalleclercq. Now it's @eclipsewebmaster which is the owner of tm4e

**Comment by akurtakov** [comment]
This should be automated process based on committer records at the foundation. Shouldn't need manual work like that.

**Comment by mickaelistria** [comment]
Now that tm4e is an Eclipse project, the repo is owned by @eclipsewebmaster and addition of "collaborators" require to go through the usual Eclipse committer election process.
@angelozerr maybe you should start a vote for @pascalleclercq as committer to TM4E? From https://dev.eclipse.org/portal/myfoundation/portal/portal.php , there is a "Nominate committer" link.
@all Make sure your GitHub id is set on https://dev.eclipse.org/site_login/myaccount.php#open_tab_accountsettings , it's a necessary setting for permissions on GitHub
@akurtakov you've closed the issue, I guess you only wanted to comment and you'd like to reopen it.

**Comment by angelozerr** [comment]
> maybe you should start a vote for @pascalleclercq as committer to TM4E

It seems that @pascalleclercq has been already nominated.

> Make sure your GitHub id is set on 

Yes it is setted, but it doesn't work. I'm waiting for @eclipsewebmaster answer.

**Comment by angelozerr** [comment]
Thanks @akurtakov !

**Pull request merged**
