### PR TITLE
CSS file isn't colored in generic editor

### LINKED ISSUE #102: CSS file isn't colored in generic editor
I'm not fully sure if its a bug or something with my configuration. When I'm opening css file in generic editor its not colored but it works ok with TextMate editor and in preferences preview. I have all tm4e plugins and LSP4E. HTML file is colored correctly. I debug it for a moment and grammar is applied to TMPresentationReconciler when generic editor is opened.
screenshot from 2017-05-22 09-55-32

### PR DESCRIPTION
**Pull request by mniewrzal**
Fixes #102

Signed-off-by: Michal Niewrzal <michal.n@zend.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
@mickaelistria you must sign your PR please.

**Comment by angelozerr** [comment]
Thanks @mniewrzal next time please sign your PR, thanks.

**Comment by angelozerr** [comment]
@mniewrzal could you redone the PR please. I don't know why I have remove your PR-( Thanks!

**Comment by mniewrzal** [comment]
Sure, no problem :)

**Pull request merged**
