### PR TITLE
Issue #69: Improve TokenizerThread

### PR DESCRIPTION
**Pull request by mickaelistria**
Use a producer/consumer pattern with a BlockingQueue.
+ Move all line index in thread to 0-based

Signed-off-by: Mickael Istria <mistria@redhat.com>

### CODE REVIEW

**Comment by mickaelistria** [comment]
There's an issue with this patch. Please stay tuned for an update.

**Comment by mickaelistria** [comment]
Ok, this new patch is good IMO.

**Comment by angelozerr** [comment]
@mickaelistria I'm playing with your PR and I'm really impressive, wow it looks like very promising. Let me some time to test it again before accepting your PR.

**Comment by angelozerr** [comment]
@mickaelistria it works like a charm, thanks! Next issue very important is https://github.com/eclipse/tm4e/issues/78 After that I think we starts having a good TextMate support

Ping me if you want that we discuss about https://github.com/eclipse/tm4e/issues/78  issue.

**Pull request merged**
