### PR TITLE
Bug #248 NullPointerException deselecting theme on Theme preference page

### PR DESCRIPTION
**Pull request by jabby**
Signed-off-by: Gautier de Saint Martin Lacaze <gautier.desaintmartinlacaze@gmail.com>

### CODE REVIEW

**Comment by mickaelistria** [comment]
Code looks ok. However, can you please bump version to 0.4.1 by the way?

**Comment by jabby** [comment]
@mickaelistria Ok I will do that in few minutes.

**Comment by mickaelistria** [comment]
pom files needs to be updated as well ;)

**Comment by jabby** [comment]
Oups, my bad. Thanks for your review.

**Comment by mickaelistria** [comment]
Thanks @jabby !

**Pull request merged**
