### PR TITLE
Issue #30: reconcilier propagate style until TM overrides it

### PR DESCRIPTION
**Pull request by mickaelistria**
Signed-off-by: Mickael Istria <mistria@redhat.com>

### CODE REVIEW

**Comment by mickaelistria** [comment]
@ainsley: would you like to review the code and check whether it works as you'd expect?

**Comment by ainsley** [comment]
Is it published to the update site?

**Comment by mickaelistria** [comment]
No, you'll have to try it locally.
Checkout the branch with `git fetch origin pull/74/head && git checkout FETCH_HEAD`, then build it with `mvn clean verify` and you'll get a locally built update-site to try it in `repository/target/repository`.

**Comment by ainsley** [comment]
ok, let me have a try

**Comment by ainsley** [comment]
@mickaelistria Pardon me for being dim, but I am having a maven build problem

----
Could not mirror                                                                        artifact osgi.bundle,org.eclipse.equinox.ds,1.5.0.v20170307-1429 into the local                                                                        Maven repository
----

Maven works in mysterious ways.

To be clear, I ran the following 4 commands in a git bash shell (on windows 10):

git clone https://github.com/eclipse/tm4e.git
cd tm4e
git fetch origin pull/74/head && git checkout FETCH_HEAD
mvn clean verify

The error was as shown above.

Perhaps the "git fetch origin pull/74/head && git checkout FETCH_HEAD" should have been two commands?

**Comment by mickaelistria** [comment]
No problem for asking ;)

> Perhaps the "git fetch origin pull/74/head && git checkout FETCH_HEAD" should have been two commands?

I don't think that would change anything.

Can you please retry again and if it fails again, put the log is some gist of fpaste and share the link to it so I can have a more detailed look?

**Comment by ainsley** [comment]
Error here .... seems to be network timeout related on one of the resources ....

https://gist.github.com/ainsley/43eb818f841825de931c8556d898e60a

**Comment by mickaelistria** [comment]
Ok, thanks. Indeed, it looks like a network issue or an erroneous mirror. Can you please try `mvn clean verify -Dtycho.disableP2Mirrors=true` to disable usage of those mirrors and see if things get better?

**Comment by ainsley** [comment]
Is "org.eclipse.tm4e.core.grammar.test.VSCodeTextMateTest"  supposed to take 10 minutes?

**Comment by ainsley** [comment]
OK, I'm trying to import the projects into Eclipse but getting the following problems.... It appears that the joni and jcodings jars are not part of the build path.

g9

Not sure how the build path works on mavenified Eclipse projects. However it should be working, it is not working.

I'm so sorry for these rookie errors. I do have experience of Eclipse development, but never with Mavenified Eclipse projects.

**Comment by mickaelistria** [comment]
To work with TM4E in the IDE, you need to have Eclipse "Plugin Development Environment" installed (Help > Install new software > Neon > ...) and optionally the[ tycho-m2e connector](https://wiki.eclipse.org/Tycho/FAQ#What_do_I_need_to_install_in_my_Eclipse_IDE_to_easily_work_with_Tycho.3F). Once you have it all installed, you should open the `target-platform/tm4e-target.target` file with the dedicated editor, and then click "Set As Target Platform" in the editor.

**Comment by angelozerr** [comment]
@mickaelistria perhaps we should add those information in the wiki, what do you think?

**Comment by mickaelistria** [comment]
> @mickaelistria perhaps we should add those information in the wiki, what do you think?

+1, or in some doc inside the repo (as it's easier to find and keep in sync than wiki)

**Comment by ainsley** [comment]
Just installed Tycho, but have to go out for a little while now, I'll follow the rest of your instructions after I return. This must be the longest delay to validating a small change you have ever faced. But I'm happy for your assistance and that after this future confirmations will be easy.

**Comment by ainsley** [comment]
Hi, the "target-platform/tm4e-target.target" file is not contained within a Java Project, so do I open this file manually using "File/Open File"?

**Comment by mickaelistria** [comment]
> Hi, the "target-platform/tm4e-target.target" file is not contained 
> within a Java Project, so do I open this file manually using 
> "File/Open File"?
>
I suggest you import the whole tm4e folder in your IDE using `File > 
Open Projects from Filesystem`. So the target-platform folder will be 
visible and you'll be able to open it with double-click.
If you're using the project explorer, you can show the structure of the 
project hierarchically with 
https://www.eclipse.org/mars/noteworthy/#_nested_hierarchical_view_of_projects

HTH

**Comment by ainsley** [comment]
> I suggest you import the whole tm4e folder in your IDE using `File >
Open Projects from Filesystem`. So the target-platform folder will be
visible and you'll be able to open it with double-click.

The 'target-platform' folder cannot be imported in the standard way as an Eclipse project, because it does not contain a ".project" file.

**Comment by mickaelistria** [comment]
But as there is a pom.xml file, `File > Open Projects from Filesystem` should detect it... Or are you using an older version of Eclipse?

**Comment by ainsley** [comment]
I'm using Neon.3, fully updated. I have PDE installed, and Tycho (as per instructions).

**Comment by ainsley** [comment]
Now I'm down to the following Eclipse errors : 

gah

**Comment by mickaelistria** [comment]
There are not as bad as they seem to be, you can try the patch even with those errors ;)

**Comment by ainsley** [comment]
Since clicking "Set As Target Platform", my main plugin project has lost access to JDT

1y

**Comment by ainsley** [comment]
I'm afraid I can't seem to build locally and can't have tm4e live peacefully alongside my existing plugin project without upending the platform on which my plugin lives.

I managed to run the "mvn clean verify -Dskiptests" command and it did complete building, but then when I tried to "Install New Software" and set the local target folder to ~projectfolder/tm4e/tm-feature/target" folder, it told me there were no features  I could use.

Quite frustrated. I really want to test this.

**Comment by mickaelistria** [comment]
The folder to use to install via update-site is `repository/target/repository`

**Comment by ainsley** [comment]
Good news!

It's all working as expected.  I don't see a flicker between typing a new character and the character being typed in. Seems to be a good and performant solution.

My grammar is extremely complex (tmLanguage file of about 2,100 lines with many complex regular expressions) so I'm very concerned about performance.  I tested this at the top and bottom of a 4,000 line file and it is very fast / instant.  Perceptually, just as good as VSCode or Ace Editor.

There was an older issue with the entire document becoming non validated. I'll keep an eye out for that issue and if it occurs again, I'll raise a new issue once I tie down the causes.

Sorry about the problems trying to sort out the development platform.  I raised an issue about an issue I found in the build so we can talk about that separately.

**Comment by angelozerr** [comment]
> There was an older issue with the entire document becoming non validated. I'll keep an eye out for that issue and if it occurs again, I'll raise a new issue once I tie down the causes.

If it's because you manage annotations (like validation, code folding, etc) in your custom editor, I suspect your problem is the same than https://github.com/eclipse/tm4e/issues/78

**Comment by mickaelistria** [comment]
Rebased and merged as 650f5b58f9b9c0b29f893ab82fd3d6e88cd8e23b

**Pull request closed without merging**
