### PR TITLE
Fixed wrong condition (it was inverted accidentally I guess)

### LINKED ISSUE #311: Wrong equals object?
Is this condition correct? https://github.com/eclipse/tm4e/blob/1ee8f06318cfed42c73fd4c2d21907acc1fee575/org.eclipse.tm4e.core/src/main/java/org/eclipse/tm4e/core/grammar/StackElement.java#L91

Note that the condition is negated:
`!Objects.equals(a.endRule, b.endRule)`

### PR DESCRIPTION
**Pull request by danipen**
Fixes #311

### CODE REVIEW

**Comment by mickaelistria** [comment]
Can you please sign the Eclipse Contributor Agreement?

**Comment by angelozerr** [comment]
Please note this code was a copy/paste from https://github.com/microsoft/vscode-textmate/blob/4f1272a1fd38d2bdd3449a4e6ee479af6babff1c/src/grammar.ts#L1480 It seems the code has changed.

**Comment by danipen** [comment]
@mickaelistria what am I supposed to fix here?
image

**Comment by mickaelistria** [comment]
I believe you can sign it at https://accounts.eclipse.org/user/eca

**Comment by danipen** [comment]
ok it seems it worked now ;-)

**Comment by mickaelistria** [comment]
Great, thanks!

**Pull request merged**
