### PR TITLE
Travis CI to run UI tests

### PR DESCRIPTION
**Pull request by mickaelistria**
See https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI

Signed-off-by: Mickael Istria <mistria@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
@mickaelistria I trust you. Can I merge it?

**Comment by mickaelistria** [comment]
I'd like to have a look at the log first. I'd also like to see a test failing on travis because of missing X server. But it seems like travis isn't running tests, is it?

**Comment by angelozerr** [comment]
> But it seems like travis isn't running tests, is it?

No I think travis is running tests. See for instance https://travis-ci.org/eclipse/tm4e/builds/216418365#L2506

**Comment by mickaelistria** [comment]
Ok, however I do not see tests in org.eclipse.tm4e.ui.tests running...

**Comment by angelozerr** [comment]
> Ok, however I do not see tests in org.eclipse.tm4e.ui.tests running...

Perhaps it's because it should follow a convention name.   https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.ui.tests/src/test/java/org/eclipse/tm4e/ui/AllTests.java should be perhaps renamed to AllTest

**Comment by mickaelistria** [comment]
Well, this works with the same Maven build on Jenkins: https://hudson.eclipse.org/tm4e/job/snapshot/org.eclipse$org.eclipse.tm4e.ui.tests/19/testReport/

**Comment by angelozerr** [comment]
@pascalleclercq could you help us please for this issue. Thanks!

**Comment by angelozerr** [comment]
@mickaelistria what about this PR?

**Comment by mickaelistria** [comment]
I'm confused with this one. The build always fail with 
```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.tm4e.repository raw:0.1.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):0.1.0-SNAPSHOT
[ERROR]   Missing requirement: tm-feature.feature.group 0.1.0.201709111040 requires 'org.eclipse.tm4e.markdown [0.1.0.201704131317]' but it could not be found
[ERROR]   Cannot satisfy dependency: org.eclipse.tm4e.repository raw:0.1.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):0.1.0-SNAPSHOT depends on: tm-feature.feature.group 0.0.0
[ERROR] 
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
```
whereas a local build always work for me and Jenkins. I see there seems to be an issue in the way the qualifier for the org.eclipse.tm4e bundle is computed: it should be 0.1.0.201704131317 (and it is for me and Jenkins) according to the last commit that changed this bundle, but travis log says it's 0.1.0.201704260036 there.
I'll trigger debug mode and ultra-verbose output on travis to hopefully find what causes this difference.

**Comment by mickaelistria** [comment]
By the way, at least, this patch does enable and run all tests ;)

**Comment by mickaelistria** [comment]
I've been digging a bit more, and it seems like travis actually builds a different commit:
```
$ git show HEAD
commit dacfd452f308b802569dad46e3d54b61f7182864 (HEAD)
Merge: 0943060 a1c0e46
Author: Mickael Istria <mistria@redhat.com>
Date:   Mon Sep 11 15:08:07 2017 +0000
    Merge a1c0e463b04e5cc7f97e90d1139edc54e7c83ae3 into 0943060912199e2ba5ba07354290ff3b0a4c3b5a
```

**Comment by mickaelistria** [comment]
I don't think we're going to invest more in Travis CI, we'd better use the Jenkins instance provided by Eclipse Foundation.

**Pull request closed without merging**
