### PR TITLE
Complete unfinished sentence in readme

### LINKED ISSUE #205: Incomplete readme
The Readme seems to be chopped off. The last sentence states:

> Becoming a committer: as usual with Eclipse.org projects, anyone who's made significant contributions and who

The second part of the sentence is missing. 😉

### PR DESCRIPTION
**Pull request by PyvesB**
This will hopefully close #205.

Signed-off-by: Pierre-Yves B. pyvesdev@gmail.com

### CODE REVIEW

**Comment by mickaelistria** [comment]
Nice touch ;)
I'd like to merge it, but Eclipse ECA bot complains. Did you sign the Eclipse Contributor Agreement with the same email address as the one in the signed-off footer?

**Comment by mickaelistria** [comment]
Ah ok I see: the signed-off-by must be in the commit, not in the PR. Please add Signed-Off-By in your commit.

**Comment by PyvesB** [comment]
This should do the trick - I thought it was in the PR's description as I noticed a few maintainers seemed to be doing that.

**Comment by mickaelistria** [comment]
Thanks. The PR description is usually a copy of the commit description which explains why you see it there.

**Comment by PyvesB** [comment]
That makes sense. Thanks for merging, arguably not a massive contribution, but every bit of improvement counts!

**Pull request merged**
