### PR TITLE
fix: On enter rule don't use the proper insert spaces / tab width when those settings are changed

### LINKED ISSUE #460: On enter rule don't use the proper insert spaces / tab width when those settings are changed
As the compute of insert spaces / tabs is cached here https://github.com/eclipse/tm4e/blob/cb5f4728cd3f0f1b2eaa4f2836519309ffacd20c/org.eclipse.tm4e.languageconfiguration/src/main/java/org/eclipse/tm4e/languageconfiguration/internal/LanguageConfigurationAutoEditStrategy.java#L283 there is a bug with on enter rule which is not updated when those settings are changed.

I noticed that while my editorconfig implementation. See the following demo:

JSONEditorConfigDemo

In the demo the jsonc file have spaces (we don't see that, but it was initialized with that). When this settings is changed with tabs and when we press on on enter between {}, it generates spaces instead of tabs. It is because https://github.com/eclipse/tm4e/blob/cb5f4728cd3f0f1b2eaa4f2836519309ffacd20c/org.eclipse.tm4e.languageconfiguration/src/main/java/org/eclipse/tm4e/languageconfiguration/internal/LanguageConfigurationAutoEditStrategy.java#L283  was cached.

To fix this issue we should avoid having a cache and just have the capability to read the tabs / insert spaces settings from the editor preferences store. This fixes requires https://github.com/eclipse-platform/eclipse.platform.text/pull/88

I remember too that we use uggly reflection to get information of insert spaces at https://github.com/eclipse/tm4e/blob/cb5f4728cd3f0f1b2eaa4f2836519309ffacd20c/org.eclipse.tm4e.languageconfiguration/src/main/java/org/eclipse/tm4e/languageconfiguration/internal/utils/TextUtils.java#L175 we should avoid doing that.

Another uggly code is here https://github.com/eclipse/tm4e/blob/cb5f4728cd3f0f1b2eaa4f2836519309ffacd20c/org.eclipse.tm4e.languageconfiguration/src/main/java/org/eclipse/tm4e/languageconfiguration/internal/LanguageConfigurationAutoEditStrategy.java#L293 to get the editor of the IAutoEditStrategy I created an issue at https://github.com/eclipse-platform/eclipse.platform.text/pull/108#issuecomment-1293957398 to get easily the editor just by implementing ITextEditorAware.

### PR DESCRIPTION
**Pull request by angelozerr**
On enter rule don't use the proper insert spaces / tab width when those settings are changed

Fixes #460

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
This PR requires https://github.com/eclipse-platform/eclipse.platform.text/pull/108

**Comment by mickaelistria** [comment]
Instead of looking at properties, can't we try to first deduce the insert spaces/tabs from previous lines in the file? Usually this leads to good results.

**Comment by angelozerr** [comment]
The main problem with this strategy is when you have no spaces. Ex:

`{}`

When you type enter inside `{|}` you don't know the spaces / tabs to use.

**Comment by angelozerr** [comment]
Another problem is if you have this usecase comments with tabs and editor is configured with spaces:

```json
/*
\t\t */
{|}
```

when you press on Enter, it will indent with tabs instead of spaces. 

IMHO, the on enter rules should follow the editor configuration and not the previous line of document. The on enter rule is a magic indentation, it is a kind of formatting.

vsocde uses the editor settings too for this on enter rules and not the previous line text.

**Comment by angelozerr** [comment]
@mickaelistria why you have closed this PR?

**Comment by mickaelistria** [comment]
The master branch have been deleted, it's now `main`. I'll see whether it's possible to retarget this PR.

**Comment by mickaelistria** [comment]
I've restored master, can you please try retargetting the PR? IIRC it is doable from the GitHub UI.

**Comment by angelozerr** [comment]
@mickaelistria I created a new PR at https://github.com/eclipse/tm4e/pull/517 which use activate text editor and not the ITextEditorAware which doesn't exists for the moment in platform text. I think using activate text editor for strategy is correct.

**Comment by sebthom** [comment]
@angelozerr is this PR still relevant or can we close it?

**Comment by angelozerr** [comment]
> @angelozerr is this PR still relevant or can we close it?

Yes it is relevant again, but I have not find time to rebase it from master.

**Comment by sebthom** [comment]
@angelozerr do you think this PR will ever happen? The required PR https://github.com/eclipse-platform/eclipse.platform.text/pull/108 got closed without being merged.

**Comment by sebthom** [comment]
Closing this PR for now as `ITextEditorAware` doesn't seem to be coming. https://github.com/eclipse-platform/eclipse.platform.text/pull/108 was been closed and there is no follow-up attempt in https://github.com/eclipse-platform/eclipse.platform.ui

The functional issue has already been solved by #517.

Feel free to reopen.

**Pull request closed without merging**
