### PR TITLE
Improve error handling (don't hide exception)

### PR DESCRIPTION
**Pull request by hetzge**
I got the "Unknown location for grammar ..." exception and didn't knew what went wrong because the catched exception was not added to the new exception.

### CODE REVIEW

**Comment by mickaelistria** [comment]
That's a good patch. Canyou please
* sign the Eclipse.Contributor Agreement https://accounts.eclipse.org/user/eca
* increase version of org.eclipse.tm4e.core by +0.0.1

**Comment by mickaelistria** [comment]
Thanks.
The feature version  also needs to be increased.
Also,please squash your commits into a single one,and add thr signed-off line to this single commit (`git commit --amend --signoff`) so the Eclipse.ECA checker should be happy.

**Comment by hetzge** [comment]
Sorry I think i messed it up :). Still need to improve my git skills. I will try later again.

**Comment by mickaelistria** [comment]
I think the simplest way would be
$ git fetch origin master
$ git reset --soft FETCH_HEAD hetzge:master
$ git commit --signoff
Check.content
$ git push --force

**Comment by hetzge** [comment]
Thank you very much @mickaelistria. I learned a lot. Now everything looks correct for me.

**Comment by mickaelistria** [comment]
Excellent! Thank you!

**Pull request merged**
