### PR TITLE
Fixes: Issue #281

### PR DESCRIPTION
**Pull request by GeraldMit**
Remove error for textViewer not an instance of SourceViewer

Change-Id: I6c5dbacd489b5094f0ae958f0bb40e27bb79c8b6
Signed-off-by: GeraldMit <Gerald.Mitchell@ibm.com>

### CODE REVIEW

**Comment by GeraldMit** [comment]
CI pr-merge fail, due to not changing the pom and manifest. Need to update both for UI to 0.4.3.

_[INFO] org.eclipse.tm4e.ui 0.4.2-SNAPSHOT ................. FAILURE [  3.512 s]
...
[INFO] BUILD FAILURE
...
[ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:2.4.0:compare-version-with-baselines (compare-version-with-baseline) on project org.eclipse.tm4e.ui: Only qualifier changed for (org.eclipse.tm4e.ui/0.4.2.202109261703). **Expected to have bigger x.y.z than what is available in baseline** (0.4.2.202011041352) -> [Help 1]_

**Comment by GeraldMit** [comment]
The change for the Feature for 0.4.3 seems like it should not be changed, so 

_[INFO] **org.eclipse.tm4e.feature 0.4.3-SNAPSHOT** ............ FAILURE [  2.363 s]
...
[INFO] BUILD FAILURE
...
[INFO] [jenkins-event-spy] Generated /home/jenkins/agent/workspace/TM4E_PR-282@tmp/withMaven8f9189e4/maven-spy-20210926-195330-41014236636667240609809.log
[ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:2.4.0:compare-version-with-baselines (compare-version-with-baseline) on project **org.eclipse.tm4e.feature**: Only qualifier changed for (org.eclipse.tm4e.feature.feature.jar/0.4.3.202109261944). Expected to have bigger **x.y.z** than what is available in baseline (0.4.3.202109010808) -> [Help 1]_

**Comment by mickaelistria** [comment]
The message is right and IMO explicit. Just increase the version to 0.4.4.

**Comment by GeraldMit** [comment]
@mickaelistria ok that is fine I have advanced the feature number; I was worried about the release version and plans numbers in RELEASE_NOTES.md and  https://projects.eclipse.org/projects/technology.tm4e, and if I was being disruptive as I was just bug fixing and not aware if the feature version planning for x.y.z had a significance I was disrupting by changing to 0.4.4.

**Comment by mickaelistria** [comment]
Thanks for the patch.
Note that Change-Id is generally useless with GitHub, it's a Gerrit-specific thing. And the "Signed-Off-By" footer isn't required any more at Eclipse.org.

**Pull request merged**
