### PR TITLE
Issue #63: connect sample grammars to Generic Editor

### PR DESCRIPTION
**Pull request by mickaelistria**
Signed-off-by: Mickael Istria <mistria@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
@mickaelistria perhaps we should have a new plugin sample with Generic Editor, no?

**Comment by mickaelistria** [comment]
I don't think it would be that helpful. This plugin is about sample, not production and the dependency to generic editor is optional.
What issue are you trying to avoid by moving the extension in another bundle?

**Comment by angelozerr** [comment]
> What issue are you trying to avoid by moving the extension in another bundle?

If user have no Oxygen, it will have errors in the plugin.xml. More with Generic Editor you need just extension point (no need Java code). It will show quickly that Generic Editor is more extensible than classic TextEditor.

**Comment by mickaelistria** [comment]
@angelozerr if you don't mind, I'd rather see this merged as it, and maybe extracted to a separate bundle later, as this is not very high priority.

**Comment by angelozerr** [comment]
No problem @mickaelistria, thanks!

**Pull request merged**
