### PR TITLE
feat: #572 Theme replicating the coloring of the WTP XML editor

### PR DESCRIPTION
**Pull request by kevloral**
It is not perfect (some items share the same CSS), but it is close enough.

### CODE REVIEW

**Comment by angelozerr** [comment]
Thanks @kevloral !

Could you add a screenshot with a sample just to see the result of your PR please.

**Comment by angelozerr** [comment]
Perhaps we should find a new name than Tradional? WTP for instance?

I suggest too to add your theme in the extensionpoint https://github.com/eclipse/tm4e/blob/88bb9c8d20b5c0bfb11573766fa709bba38323bf/org.eclipse.tm4e.ui/plugin.xml#L44 in order to TM4E provides this new theme.

**Comment by kevloral** [comment]
The theme has been renamed (now it is called _WTP XML Classic_) and has been added to the plugin descriptor.

**Comment by sebthom** [comment]
@kevloral can you please bump the minor version in the plugin.xml and the pom.xml of the tm4e.ui plugin. This should fix the build error

**Comment by kevloral** [comment]
It seems Jenkins is failing because the artifact version has not been increased from the baseline (it is still 0.7.0). Would you like me to increase it (0.7.1?) or would you rather do it yourselves?

**Comment by kevloral** [comment]
Sure, but I do not know the policy you have wrt versioning. Would 0.7.1 be fine? Or should it be 0.8.0?

**Comment by kevloral** [comment]
Feature (_org.eclipse.tm4e.feature_) version updated (0.6.0 -> 0.7.0) too.

**Comment by mickaelistria** [comment]
GitHub says "@kevloral closed this by deleting the head repository". Is this intended?

**Pull request closed without merging**
