### PR TITLE
Test integration with Generic Editor

### PR DESCRIPTION
**Pull request by mickaelistria**
Signed-off-by: Mickael Istria <mistria@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
@mickaelistria the travis seems not stopped. Do you think it could be have an infinity loop with this issue?

**Comment by mickaelistria** [comment]
seems to be the samo for all PRs, no?

**Comment by angelozerr** [comment]
> seems to be the samo for all PRs, no?

Yes but I had the impression this problem was appeared when this issue was done, but not sure for that.

**Comment by mickaelistria** [comment]
The log on travis seems totally empty. I don't know what can cause that. A local `mvn clean verify` works.

**Comment by angelozerr** [comment]
I don't know the problem -( If you have time to investigate the problem that's cool, otherwise I will try to see when I will have time.

**Comment by angelozerr** [comment]
Thanks @mickaelistria !

**Pull request merged**
