### PR TITLE
#246 Use comment block hotkey on mac similar to JDT

### PR DESCRIPTION
**Pull request by xcariba**
Changed macOS block comment hotkeys. Now it is more consistent with Eclipse JDT

### CODE REVIEW

**Comment by mickaelistria** [comment]
Can you please amend you commit to add the "Signoff" info so the Eclipse Contributor Agreement tool should be happier?

**Comment by xcariba** [comment]
Fixed commit

**Comment by mickaelistria** [comment]
Same as @jabby , merging.

**Comment by mickaelistria** [comment]
Thanks a lot @xcariba !
This change will be available in https://download.eclipse.org/tm4e/snapshots/ in a few minutes, when https://ci.eclipse.org/tm4e/job/TM4E/job/master/4/ completes.

**Pull request merged**
