### PR TITLE
Don't report errors to be consistent with the rest of the class

### PR DESCRIPTION
**Pull request by iloveeclipse**
Fixes https://github.com/eclipse/tm4e/issues/661

### CODE REVIEW

**Comment by sebthom** [comment]
Do you think instead of swallowing all exceptions we could just ignore logging if a filenotfoundexception is thrown? or log with debug level?

**Comment by iloveeclipse** [comment]
```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:4.0.4:validate-version (default-validate-version) on project org.eclipse.tm4e.ui: Unqualified OSGi version 0.9.1.qualifier must match unqualified Maven version 0.9.0-SNAPSHOT for SNAPSHOT builds -> [Help 1]
```
I don't see what is expected now.
- If I don't update manifest, build complains the version hasn't changed.
- If I update manifest, it complains, it doesn't match old version

**Comment by sebthom** [comment]
I'm looking into it right now.

**Comment by sebthom** [comment]
can you give this a try? https://github.com/eclipse/tm4e/pull/663

**Pull request closed without merging**
